### ISSUE TITLE
Not working in Symfony 2.6

### ISSUE THREAD

**Issue by smajazayeri** [stephanecollot/DatetimepickerBundle#18]
Hi there,

I followed all steps mentioned in the readme. It didn't work for me. I created my from through createFormBuilder in my controller. Is it one reason?
$form = $this->createFormBuilder()
 ->add('createdAt', 'collot_datetime');

What's rendered in my view is an input form with type=text. It seems Symfony didn't verify the collot_datetime as a form type.

**Comment by codeyourweb** [comment]
same issue for me (symfony 2.7), any idea how to fix this?

**Comment by smajazayeri** [comment]
I used another library as I haven't received any response for this issue.

**Comment by fcpauldiaz** [comment]
same issue for me in symfony 2.7.7

**Comment by fcpauldiaz** [comment]
Forget my last comment, I forgot to add "{{ form_stylesheet(form) }}" and now it works great
